apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-jzldbibt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-jzldbibt:63d263e411e5f616a1c8232b9c4aebc157e247e5@sha256:ee3b0c67384fe518078b8a9252b39867f4598e6f1b5d5d882bd43ffe0c933d78
          name: container-image
